### ISSUE TITLE
Docker Image / tricks.py issues

### ISSUE THREAD

**Issue by AlarmingAppointment9** [remicres/otbtf_tutorials#5]
Hi,

I was wanting to see if I could get some assistance with completing the step 5.4 generating the model, where `tricks.py` is used to generate models used further in the tutorial "Tokyo Dataset - Patch-Based Classification". I see there are 2 other issues that have been raised on this subject, but they seem to be fixed by a naming convention `CreateSaveModel`

I am using the docker image mdl4eo/otbtf2.4:cpu, trying to run `create_model1.py`, I have run the PYTHONPATH command
`export PYTHONPATH=$PYTHONPATH:/work/otb/otb/Modules/Remote/otbtf/python/`
But every time I still get the error 
`ModuleNotFoundError: No module named 'tricks'`

I am not that familiar with using docker images or PYTHONPATH, so am not sure where I am to run the PYTHONPATH command? 

Am I supposed to run the PYTHONPATH command from my local system? Or from the docker container?

I can `echo $PYTHONPATH`, with the correct response from my local system. I am currently running the 
`python3 create_model1.py "model1"`
from the directory with the correct python file.

How does the `tricks.py` file in the docker image get accessed by my local system Python?  

Happy to give further information if needed?

**Comment by remicres** [comment]
Hi,

> I see there are 2 other issues that have been raised on this subject, but they seem to be fixed by a naming convention `CreateSaveModel`

Yes, there were some issues regarding the naming convention of the create SavedModel function, but that is not related here.

> Am I supposed to run the PYTHONPATH command from my local system? Or from the docker container?

You must run all commands from inside your docker container. The otbtf docker containers are ready to start working with the libraries without installing and compiling everything.

> I am not that familiar with using docker images or PYTHONPATH, so am not sure where I am to run the PYTHONPATH command?

In the **mdl4eo/otbtf2.4:cpu** docker image, the `PYTHONPATH` should already be defined, and you don't have to set it manually anymore :smiley: In addition, since **otbtf version 2.4**, the OTB/TensorFlow files have moved from `/work` to `/opt` (installed files) and `/src` (sources files).

# Ok, now how to?

First, you start an interactive session with the docker image:

```
docker run -ti mdl4eo/otbtf2.4:cpu bash
```

Note that here, `-ti` stands for interactive session. And from this point, your shell in from **inside** the docker container. To exit it, just type `exit`. When you re-run it, every environment variables, files, are reset to the docker image initial state. That why you might need later to mount volumes (to save your results, etc). You can take a look in the [docker use documentation](https://github.com/remicres/otbtf/blob/develop/doc/DOCKERUSE.md) for further help: how to mount data volumes, etc. There is various ways to run docker containers, and this one might not be adapted to your workflow, I strongly recommend to read quickly the docker use, to familiarize with the ways to use docker.

Once inside the container, you can check that the `PYTHONPATH` is well configured. `PYTHONPATH` is an environment variable which tells python where to look in order to import some new modules, and we have to tell python where `tricks.py` is in the system.

```
otbuser@40226a4a5dfc:~$ echo $PYTHONPATH
/opt/otbtf/lib/python3/site-packages:/opt/otbtf/lib/otb/python:/src/otbtf/python
```

Here, everything looks fine: if you look in the `/src/otbtf/python` folder then you can see `tricks.py`.

Is that solving your issue?

**Comment by AlarmingAppointment9** [comment]
Hi Remi,

Thankyou for the quick response and information.

I can run `echo $PYTHONPATH` from within the container, which gives the response you detailed above.

I have managed to get the process `python3 create_model1.py "model1"` working now. I followed your process for 'Fix volume ownership issue' on [docker use documentation](https://github.com/remicres/otbtf/blob/develop/doc/DOCKERUSE.md) 

Once I had mounted my data volumes (which I wasn't doing before!) and changed my UID and GID to something other than 1000, it all worked.

Looking forward to continuing on the journey!
